[package]
name = "cakeman"
version = "0.1.0"
description = "A no-nonsense package manager for C/C++"
license = "MIT"
repository = "https://github.com/ManiProjs/cakeman.git"
edition = "2024"

[[bin]]
name = "cman"
path = "./src/main.rs"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.5", features = ["derive"] }
directories = "6.0.0"
dirs = "6.0.0"
git2 = { version = "0.21.0", features = ["vendored-openssl", "https"] }
oauth2 = "5.0.0"
octocrab = "0.54.1"
owo-colors = "4.3.0"
reqwest = { version = "0.13.4", features = ["blocking", "form", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
toml_edit = "0.25.13"
webbrowser = "1.2.2"
