use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::terminal;

pub fn execute(name: Option<String>) -> Result<()> {
    let creating_new_directory = name.is_some();

    let current_dir = std::env::current_dir()?;

    let (project_path, project_name) = match name {
        Some(name) => {
            let path = Path::new(&name);

            (path.to_path_buf(), name)
        }

        None => {
            let name = current_dir
                .file_name()
                .unwrap()
                .to_string_lossy()
                .to_string();

            (current_dir.clone(), name)
        }
    };

    if creating_new_directory && project_path.exists() {
        terminal::error("Directory already exists");
        return Ok(());
    }

    terminal::info(&format!("Initializing Cakeman project '{}'", project_name));

    let src_dir = project_path.join("src");

    fs::create_dir_all(&src_dir)?;

    let manifest = format!(
        r#"[package]
name = "{0}"
version = "0.1.0"
type = "binary"
language = "c"

[dependencies]
"#,
        project_name
    );

    fs::write(project_path.join("Cake.toml"), manifest)?;

    fs::write(
        src_dir.join("main.c"),
        r#"// Generated by Cakeman

#include <stdio.h>

int main(void) {
    printf("Hello from Cakeman!\n");
    return 0;
}
"#,
    )?;

    fs::write(
        project_path.join("Cake.lock"),
        "# This file is generated by Cakeman.\n",
    )?;

    terminal::success("Project initialized successfully!");

    Ok(())
}
